version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      
#Removed mongo-express entry <here> as it's redundant for this POC.

  sb-app:
    build: .
    container_name: "docker-sb-app"
    restart: always
    ports:
      - 5001:8181
    depends_on:
      - mongodb
#Removed wait script entry. https://github.com/ufoscout/docker-compose-wait/blob/master/README.md
