version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    container_name: "mongodb"
    hostname: mongo
  sb-app:
    build: .
    container_name: "docker-sb-app"
    restart: always
    ports:
      - 5001:8181
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongo:27017 
   
